
import { TranslationStrings, Language } from './types';

export const TRANSLATIONS: Record<Language, TranslationStrings> = {
  'en': {
    home: 'Home',
    movie: 'Movies',
    tvShow: 'TV Shows',
    readMore: 'More',
    watchlist: 'Watchlist',
    lottery: 'Pick One!',
    subscribe: 'Subscribe',
    emailPlaceholder: 'Enter your email...',
    adminLogin: 'Admin Login',
    settings: 'Settings',
    generateNow: 'Generate Now',
    generateMovie: 'New Movie Review',
    generateTV: 'New TV Review',
    back: 'Back to List',
    lotteryTitle: 'What should you watch?',
    spin: 'Start Lottery',
    close: 'Close',
    retry: 'Try Again',
    info: 'Information',
    director: 'Director',
    actors: 'Cast',
    runtime: 'Runtime',
    links: 'External Links',
    relatedWorks: 'Other works by this director',
    adminDashboard: 'Admin Dashboard',
    manageReviews: 'Manage Reviews',
    siteSettings: 'Site Settings',
    siteNameLabel: 'Website Name',
    authorNameLabel: 'Author Name',
    visibility: 'Visibility',
    edit: 'Edit',
    delete: 'Delete',
    save: 'Save',
    cancel: 'Cancel',
    share: 'Share',
    fortuneTitle: "Today's Fortune",
    fortuneGood: 'Good Fortune',
    fortuneGreat: 'Great Fortune',
    fortuneExcellent: 'Godly Fortune',
    fortuneSmall: 'Minor Fortune',
    logout: 'Logout',
    show: 'Show',
    hide: 'Hide',
    username: 'Username',
    password: 'Password',
    login: 'Login',
    authorStyle: 'Style',
    humorous: 'Humorous',
    toxic: 'Toxic',
    sentimental: 'Sentimental',
    saveSettings: 'Save Settings',
    region: 'Region',
    year: 'Year',
    relatedByGenre: 'More from this Genre',
    copied: 'Copied!',
    season: 'Season'
  },
  'zh-TW': {
    home: '首頁',
    movie: '電影',
    tvShow: '電視劇',
    readMore: '閱讀更多',
    watchlist: '待看清單',
    lottery: '隨機抽取',
    subscribe: '訂閱電子報',
    emailPlaceholder: '輸入您的電子信箱...',
    adminLogin: '管理者登入',
    settings: '設定',
    generateNow: '立即生成',
    generateMovie: '生成電影評論',
    generateTV: '生成電視劇評論',
    back: '返回列表',
    lotteryTitle: '今天看什麼？',
    spin: '開始抽取',
    close: '結束',
    retry: '再抽一次',
    info: '相關資訊',
    director: '導演',
    actors: '演員',
    runtime: '時長',
    links: '外部連結',
    relatedWorks: '該導演的其他作品',
    adminDashboard: '管理後台',
    manageReviews: '評論管理',
    siteSettings: '網站設定',
    siteNameLabel: '網站名稱',
    authorNameLabel: '作者名稱',
    visibility: '顯示狀態',
    edit: '編輯',
    delete: '刪除',
    save: '儲存',
    cancel: '取消',
    share: '分享',
    fortuneTitle: '今日幸運簽',
    fortuneGood: '大吉',
    fortuneGreat: '中吉',
    fortuneExcellent: '上上簽',
    fortuneSmall: '小吉',
    logout: '登出',
    show: '顯示',
    hide: '隱藏',
    username: '帳號',
    password: '密碼',
    login: '登入',
    authorStyle: '風格',
    humorous: '幽默',
    toxic: '毒舌',
    sentimental: '感性',
    saveSettings: '儲存設定',
    region: '地區',
    year: '年份',
    relatedByGenre: '同類型作品',
    copied: '已複製!',
    season: '季'
  },
  'zh-CN': {
    home: '首页',
    movie: '电影',
    tvShow: '电视剧',
    readMore: '阅读更多',
    watchlist: '待看清单',
    lottery: '随机抽取',
    subscribe: '订阅电子报',
    emailPlaceholder: '输入您的电子信箱...',
    adminLogin: '管理者登录',
    settings: '设置',
    generateNow: '立即生成',
    generateMovie: '生成电影评论',
    generateTV: '生成电视剧评论',
    back: '返回列表',
    lotteryTitle: '今天看什么？',
    spin: '开始抽取',
    close: '结束',
    retry: '再抽一次',
    info: '相关信息',
    director: '导演',
    actors: '演员',
    runtime: '时长',
    links: '外部链接',
    relatedWorks: '该导演的其他作品',
    adminDashboard: '管理后台',
    manageReviews: '评论管理',
    siteSettings: '网站设置',
    siteNameLabel: '网站名称',
    authorNameLabel: '作者名称',
    visibility: '显示状态',
    edit: '编辑',
    delete: '删除',
    save: '保存',
    cancel: '取消',
    share: '分享',
    fortuneTitle: '今日幸运签',
    fortuneGood: '大吉',
    fortuneGreat: '中吉',
    fortuneExcellent: '上上签',
    fortuneSmall: '小吉',
    logout: '登出',
    show: '显示',
    hide: '隐藏',
    username: '账号',
    password: '密码',
    login: '登录',
    authorStyle: '风格',
    humorous: '幽默',
    toxic: '毒舌',
    sentimental: '感性',
    saveSettings: '保存设置',
    region: '地区',
    year: '年份',
    relatedByGenre: '同类型作品',
    copied: '已复制!',
    season: '季'
  }
};

export const FORTUNES: Record<Language, string[]> = {
  'en': [
    'Your eyes will be blessed with cinematic gold today.',
    'A plot twist in your life is coming, prepare popcorn.',
    'You are the main character of a feel-good indie movie.',
    'Avoid horror movies today; your luck is already scary.',
    'A surprise recommendation will change your weekend plans.'
  ],
  'zh-TW': [
    '今日適合看熱血大作，燃燒你的鬥志！',
    '生活就像電影，今天的你是奧斯卡影帝。',
    '桃花運正如浪漫喜劇般悄悄降臨。',
    '這部電影會給你帶來意想不到的靈感與好運。',
    '今天的你，運氣比主角光環還要耀眼！'
  ],
  'zh-CN': [
    '今日适合看熱血大作，燃燒你的鬥志！',
    '生活就像电影，今天的你是奥斯卡影帝。',
    '桃花运正如浪漫喜剧般悄悄降临。',
    '这部电影会给你带来意想不到的灵感与好运。',
    '今天的你，运气比主角光環还要耀眼！'
  ]
};

export const LOCALIZED_GENRES: Record<Language, Record<string, string>> = {
  'en': {
    'Action': 'Action', 'Adventure': 'Adventure', 'Animation': 'Animation', 'Comedy': 'Comedy',
    'Crime': 'Crime', 'Documentary': 'Documentary', 'Drama': 'Drama', 'Family': 'Family',
    'Fantasy': 'Fantasy', 'History': 'History', 'Horror': 'Horror', 'Music': 'Music',
    'Mystery': 'Mystery', 'Romance': 'Romance', 'Sci-Fi': 'Sci-Fi', 'TV Movie': 'TV Movie',
    'Thriller': 'Thriller', 'War': 'War', 'Western': 'Western', 'Action & Adventure': 'Action & Adventure',
    'Kids': 'Kids', 'News': 'News', 'Reality': 'Reality', 'Soap': 'Soap', 'Talk': 'Talk', 'War & Politics': 'War & Politics'
  },
  'zh-TW': {
    'Action': '動作', 'Adventure': '冒險', 'Animation': '動畫', 'Comedy': '喜劇',
    'Crime': '犯罪', 'Documentary': '紀錄片', 'Drama': '劇情', 'Family': '家庭',
    'Fantasy': '奇幻', 'History': '歷史', 'Horror': '恐怖', 'Music': '音樂',
    'Mystery': '懸疑', 'Romance': '愛情', 'Sci-Fi': '科幻', 'TV Movie': '電視電影',
    'Thriller': '驚悚', 'War': '戰爭', 'Western': '西部', 'Action & Adventure': '動作冒險',
    'Kids': '兒童', 'News': '新聞', 'Reality': '真人秀', 'Soap': '肥皂劇', 'Talk': '脫口秀', 'War & Politics': '戰爭與政治'
  },
  'zh-CN': {
    'Action': '动作', 'Adventure': '冒险', 'Animation': '动画', 'Comedy': '喜剧',
    'Crime': '犯罪', 'Documentary': '纪录片', 'Drama': '剧情', 'Family': '家庭',
    'Fantasy': '奇幻', 'History': '历史', 'Horror': '恐怖', 'Music': '音乐',
    'Mystery': '悬疑', 'Romance': '爱情', 'Sci-Fi': '科幻', 'TV Movie': '电视电影',
    'Thriller': '惊悚', 'War': '战争', 'Western': '西部', 'Action & Adventure': '动作冒险',
    'Kids': '儿童', 'News': '新闻', 'Reality': '真人秀', 'Soap': '肥皂剧', 'Talk': '脱口秀', 'War & Politics': '战争与政治'
  }
};

export const GENRE_MAP: Record<number, string> = {
  28: 'Action', 12: 'Adventure', 16: 'Animation', 35: 'Comedy', 80: 'Crime',
  99: 'Documentary', 18: 'Drama', 10751: 'Family', 14: 'Fantasy', 36: 'History',
  27: 'Horror', 10402: 'Music', 9648: 'Mystery', 10749: 'Romance', 878: 'Sci-Fi',
  10770: 'TV Movie', 53: 'Thriller', 10752: 'War', 37: 'Western',
  10759: 'Action & Adventure', 10762: 'Kids', 10763: 'News', 10764: 'Reality',
  10765: 'Sci-Fi & Fantasy', 10766: 'Soap', 10767: 'Talk', 10768: 'War & Politics'
};
